package com.fouriApps.model.AM;


import java.sql.SQLSyntaxErrorException;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;

import javax.faces.model.SelectItem;

import oracle.jbo.server.ViewObjectImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 21 14:22:59 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DynamicReports_AMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DynamicReports_AMImpl() {
    }


    /**
     * Container's getter for Projects_ROVO1.
     * @return Projects_ROVO1
     */
    public ViewObjectImpl getProjects_ROVO1() {
        return (ViewObjectImpl)findViewObject("Projects_ROVO1");
    }

    /**
     * Container's getter for Property_ROVO1.
     * @return Property_ROVO1
     */
    public ViewObjectImpl getProperty_ROVO1() {
        return (ViewObjectImpl)findViewObject("Property_ROVO1");
    }

    /**
     * Container's getter for Report_ROVO1.
     * @return Report_ROVO1
     */
    public ViewObjectImpl getReport_ROVO1() {
        return (ViewObjectImpl)findViewObject("Report_ROVO1");
    }

    /**
     * Container's getter for ReportFormat_STA1.
     * @return ReportFormat_STA1
     */
    public ViewObjectImpl getReportFormat_STA1() {
        return (ViewObjectImpl)findViewObject("ReportFormat_STA1");
    }

    /**
     * Container's getter for Customer_ROVO1.
     * @return Customer_ROVO1
     */
    public ViewObjectImpl getCustomer_ROVO1() {
        return (ViewObjectImpl)findViewObject("Customer_ROVO1");
    }

    /**
     * Container's getter for SOA_Summary_ROVO1.
     * @return SOA_Summary_ROVO1
     */
    public ViewObjectImpl getSOA_Summary_ROVO1() {
        return (ViewObjectImpl)findViewObject("SOA_Summary_ROVO1");
    }
}
